services:
  nacos:
    image: nacos/nacos-server:v2.4.3
    container_name: nacos
    environment:
      - MODE=standalone
      - NACOS_AUTH_ENABLE=false
      - JVM_XMS=256m
      - JVM_XMX=256m
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - nacos-data:/Users/gin/Desktop/JAVA/nacos/data
      - nacos-logs:/Users/gin/Desktop/JAVA/nacos/logs

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass difyai123456
    volumes:
      - redis-data:/data

volumes:
  nacos-data:
  nacos-logs:
  redis-data: